---
# tasks file riakcs-configure

- name: Template riakcs
  template: src=riak-cs.conf.j2 dest=/etc/riak-cs/riak-cs.conf owner=riakcs group=riak

- name: Template app.config for Riak
  template: src=app.config.j2 dest=/etc/riak/app.config owner=riak group=riak

- name: Copy the Riak app.config
  copy: src=app.config dest=/etc/riak/app.config owner=riak group=riak
